name: turtlebot4_simulator_ci

on: [push, pull_request]

jobs:
  turtlebot4_humble_ci:
    name: Humble
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: humble
          import-token: ${{ secrets.GITHUB_TOKEN }}
          package-name:
            turtlebot4_ignition_bringup
            turtlebot4_ignition_gui_plugins
            turtlebot4_ignition_toolbox
